### ISSUE TITLE
Allow strings (not just urls) as input, and remove tracking params on all given links.

### ISSUE THREAD

**Issue by dessalines** [jendrikw/clearurls#3]
It'd be hugely helpful to either add, or alter the existing function to be  `fn clear_urls(input: &str)`, and step through any number of urls, while ignoring other text.

IE say there's a comment with multiple links, and some other text:

```rust
test(
  "This is a [markdown link](http://example.com/?&&&&), and another: http://example.com/?&&&&",
  "This is a [markdown link](http://example.com/), and another http://example.com/",
);
```

**Comment by jendrikw** [comment]
This would require a full markdown parser, which is not a problem by itself, but I'm guessing lemmy has to parse it anyways, so doing it twice seems wasteful.

**Comment by dessalines** [comment]
A markdown parser isn't necessary, you only need to identify and parse links in the given text, and replace them at their positions. Plus you wouldn't even know the format being given to this function anyway.

**Comment by jendrikw** [comment]
Implemented and published in 0.0.2 https://crates.io/crates/clearurls/0.0.2

**Comment by jendrikw** [comment]
Let me know if you need anything else

**Comment by dessalines** [comment]
Sweet, thx!
