### ISSUE TITLE
Use a submodule for the ClearURLs json data?

### ISSUE THREAD

**Issue by dessalines** [jendrikw/clearurls#6]
What are your thoughts on adding https://github.com/ClearURLs/Rules as a submodule? That way you wouldn't have to do manual updates / refetches of that file, but link to the source data directly.

**Comment by jendrikw** [comment]
It wouldn't provide much of a benefit, as I'd still have to publish an update to crates.io

**Comment by dessalines** [comment]
Gotcha.
